[project]
name = "snowdown"
version = "0.1.0"
description = "SnowDown system"
readme = "snowdown.md"
requires-python = ">=3.10"

[project.scripts]
snowdown = "src.main:main"

[tool.setuptools.packages.find]
where = ["src"]
