[project]
name = "snowdown"
version = "0.1.5"
description = "SnowDown system"
readme = "README.md"
requires-python = ">=3.10"

[project.scripts]
snowdown = "snowdown.main:main"
[tool.setuptools.packages.find]
where = ["src"]
